name = "screengolf"
compatibility_date = "2025-06-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "screengolf"
database_id = "54bca71f-e4bc-4530-97a7-f4cfeeeca9ce"
